name: Build and Deploy website with Azure Function
on:
  push:
    branches:
      - main
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'api'
  DOTNET_VERSION: '6.0.x'
jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: ''
          api_location: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          output_location: ''
  build-and-deploy-azure-function:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Setup DotNet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build Azure Function
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      - name: Deploy Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: 'ContactFormWithAzure'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}